apiVersion: v1
kind: Service
metadata:
    name: "k8ticketspoc-4917"
    labels:
        app: "k8ticketspoc-4917"
spec:
    type: LoadBalancer
    ports:
    - port: 2022
      targetPort: 2022
      protocol: TCP
      name: http
    selector:
        app: "k8ticketspoc-4917"